name: Atualizar base de despesas

on:
  schedule:
    - cron: "0 11 * * *"   # TODO dia às 08:00 UTC -3
  workflow_dispatch:

jobs:
  atualizar-despesas:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Executar despesas.py
        env:
          API_TOKEN_SF: ${{ secrets.API_TOKEN_SF }}
        run: |
          python despesas.py

      - name: Commit dos dados atualizados
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add base_despesas
          git commit -m "Atualização automática diária da base"
          git push
